name: Algorithms Workflow

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    name: Project Installation and Running Test Cases
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with: 
          node-version: ${{ matrix.node-version }}

      - name: Install the project
        run: npm install

      - name: Test the project
        run: npm test
